[package]
name = "query_algebrizer_traits"
version = "0.0.1"
edition = "2024"
workspace = ".."

[lib]
name = "query_algebrizer_traits"
path = "lib.rs"

[dependencies]
anyhow = "1"
thiserror = "1"
[dependencies.edn]
path = "../edn"

[dependencies.core_traits]
path = "../core-traits"
